from https://talonvoice.slack.com/archives/C03UHK9CGHY/p1697448097179639?thread_ts=1690662546.322159&cid=C03UHK9CGHY
27-feb-2024



Edit the gaze_ocr_talon.py, replacing the relevant section with:  (if you search for that log message, you'll find it)
if setting_ocr_use_talon_backend.get() and not ocr:
    logging.info("Talon OCR not available, will rely on external support.")
    ocr_reader = screen_ocr.Reader.create_fast_reader(
    radius=200, homophones=homophones,
    tesseract_data_path = r"/usr/share/tesseract-ocr/5/tessdata",
    tesseract_command = r"/usr/bin/tesseract"
)
sudo apt-get install tesseract-ocr
cd ~/.talon/
python3 -m venv .venv
source .venv/bin/activate
pip install screen-ocr[tesseract]
restart talon, and hopefully it works!


As an addition to the above, if you see an error where talon is expecting the tesseract trained data to be in a specific directory, search for the trained data:
sudo find / -iname "*eng.traineddata*"
Then copy the eng.traineddata file to where talon expects. Create the directory path first if needed.
:+1:
1



Nathan's approach worked for me. However, for some reason, I have Tesseract version 4, So I needed different  File path as per below:
 > sudo updatedb
> locate tessdata
/usr/share/tesseract-ocr/4.00/tessdata
 Also, whatever reason  I am running both pip and pip3 and had  To muck about uninstalling and reinstalling things ala
pip uninstall screen-ocr[tesseract]
pip3 uninstall screen-ocr[tesseract]
sudo apt remove screen-ocr
pip install screen-ocr[tesseract]
pip3 install screen-ocr[tesseract]
